# Default Colors
[colors.primary]
background = "#323232"
foreground = "#ffffff"

[colors.cursor]
cursor = "#d6d6d6"

[colors.selection]
background = "#5b5b5b"
text = "#323232"

# Normal colors
[colors.normal]
black = "#323232"
red = "#d25252"
green = "#7fe173"
yellow = "#ffc66d"
blue = "#4098ff"
magenta = "#f57fff"
cyan = "#bed6ff"
white = "#eeeeec"

# Bright colors
[colors.bright]
black = "#535353"
red = "#f07070"
green = "#9dff90"
yellow = "#ffe48b"
blue = "#5eb7f7"
magenta = "#ff9dff"
cyan = "#dcf4ff"
white = "#ffffff"
